sudo: false

os: osx
osx_image: xcode10.1
language: node_js
node_js: "10"

env:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache: npm

before_install:
  - if [[ `npm -v` != 6* ]]; then npm install -g npm@6; fi

install:
  - npm install

script:
  - npm test
  - npm run package-mac
  - ls -l ./release

matrix:
  allow_failures:
    - node_js: node
